---
- name: Configura VM + WebLogic 14c Cluster Lab
  hosts: weblogic
  become: true
  gather_facts: true

  roles:
    - role: java
      tags: [java]

    - role: weblogic
      tags: [weblogic]

    - role: domain
      tags: [domain]

    - role: deploy
      tags: [deploy]
